
version: "3"
services:
  app:
    container_name: app
    restart: on-failure:2
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    env_file: .env
     
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    env_file: .env