
version: "3"
services:
  app:
    container_name: app
    restart: on-failure:2
    build: .
    ports:
      - "6566:6566"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"